name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
          cache: true
      - run: go build
      - run: go test
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
          cache: true
      - run: go vet
      - run: go install honnef.co/go/tools/cmd/staticcheck@latest && staticcheck
      - run: |
          need_fmt=$(gofmt -l .)
          [ -z "$need_fmt" ] && exit 0
          echo 'Some files require formatting:'
          echo "\n$need_fmt\n"
          echo 'Run `go fmt ./...`'
          exit 1
